### PR TITLE
Input arg substitution as consts

### PR DESCRIPTION
**Pull request by IgorErin**
- Strange error about argument/parameter count mismatch 
- Input arg represented as `Const` in ast. Perhaps not the best solution, but perhaps the simplest
  - So we should support `Const` automaton for argument passing

### CODE REVIEW

**Comment by IgorErin** [comment]
@WoWaster Could you take a look about https://github.com/PeanutProver/PeanutProver/issues/17

**Comment by WoWaster** [comment]
I'll take a closer look at your code in a second. Right now I have a question: do we really need .NET7.0? I'd like to stick to LTS versions of .NET in this project. If .NET7.0 isn't really required right now, let's stick with .NET6.0 and bump everything to .NET8.0 as soon as it is released.

**Comment by WoWaster** [comment]
Also, please rebase on main branch since I merged previous PR.

**Review by WoWaster — COMMENTED** [review]
Your last commit can be squashed into penultimate one

**Comment by IgorErin** [comment]
Sure. I'm all about you writing tests on the cli

**Pull request closed without merging**
